### ISSUE TITLE
i2d is not a supported system type

### ISSUE THREAD

**Issue by rkinnc75** [flz/iaqualink-py#18]
Example logic call and results

pi@raspberrypi:~ $ cat aqua.py

#!/usr/bin/python

import iaqualink
from iaqualink.client import AqualinkClient
import asyncio

async def main():
    async with AqualinkClient('xxx@example.com', 'password') as c:
        print(c)
        s = await c.get_systems()
        print(s)
        d = await list(s.values())[0].get_devices()
        print(d)

if __name__=="__main__":
    asyncio.run(main())
    
    
pi@raspberrypi:~ $ python aqua.py

<iaqualink.client.AqualinkClient object at 0xb5cfb370>
i2d is not a supported system type.
{}
Traceback (most recent call last):
  File "/home/pi/aqua.py", line 16, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/aqua.py", line 12, in main
    d = await list(s.values())[0].get_devices()
IndexError: list index out of range

**Comment by flz** [comment]
As the message says, that's expected. The API isn't documented and I don't have access to one of those.

Depending on your technical abilities, you might be able to reverse engineer it by setting up a proxy (e.g. mitmproxy, CharlesProxy) and intercepting requests coming from the mobile app. I can also offer to do it for you if you give me access to it.

Either way, I won't have time to add support in the near future. The free time I have is spent getting the current codebase into shape and making it easier for people to contribute to.

**Comment by rkinnc75** [comment]
Thanks!  I've installed mitmproxy and configured it.   I've captured a
series of different GET/POST lines.  I'll see what I can do to decipher it.

**Comment by flz** [comment]
That's awesome. I've got a bunch of work in progress to make adding new systems easier but documenting the API in the first place is the hardest part.

**Comment by DarkWolf7** [comment]
Hi, has any progress been made on this? I just tried to add one of these to home assistant and running into this issue - I'd be happy to help where I can but I don't speak much Python

**Comment by tkhduracell** [comment]
There is some work going on to support i2d for Jandy IQPump [here](https://github.com/flz/iaqualink-py/issues/36). Is that the device you´re using?

**Comment by DarkWolf7** [comment]
> There is some work going on to support i2d for Jandy IQPump [here](https://github.com/flz/iaqualink-py/issues/36). Is that the device you´re using?

Yes it is!

**Comment by CLARENNE-Q** [comment]
Else: https://github.com/CLARENNE-Q/iaqualink_iqpump01
