### ISSUE TITLE
Login error on HomeAssistant 

### ISSUE THREAD

**Issue by CamTosh** [flz/iaqualink-py#37]
👋

Do you know if this issue is on the iqualink-py lib or on the Home Assistant intgreation?

## Versions:

- Home Assistant: `2023.9.1`
- iaqualink: `0.5.0`

## Error 

```
2023-09-15 12:37:37.920 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry user@something.com for iaqualink

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/tls.py", line 131, in _call_sslobject_method
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 921, in read
    v = self._sslobj.read(len)
        ^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2580)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/tls.py", line 196, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/tls.py", line 138, in _call_sslobject_method
    data = await self.transport_stream.receive()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1203, in receive
    await self._protocol.read_event.wait()
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:
```

**Comment by flz** [comment]
I don't think I've seen this failure before (https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.CancelledError).

Have you tried reloading the integration? It might have been a temporary error due to connectivity issues (or service issue).

**Comment by CamTosh** [comment]
@flz Good catch, the login is working on my computer and not my Rpi.

I have other error but these are on Home Assistant integration side

`2023-09-21 13:10:37.870 ERROR (MainThread) [homeassistant.components.iaqualink] No systems detected or supported`
